/** @type {import('stylelint').Config} */
export default {
  ignoreFiles: ["src/theme/generated/**", "dist/**", "dist_keycloak/**"],
  rules: {
    // Every color must come from a `--color-*` custom property generated by
    // packages/design-tokens -- never a raw literal. See CLAUDE.md.
    "color-no-hex": true,
    "color-named": "never",
    "function-disallowed-list": ["rgb", "rgba", "hsl", "hsla"],
  },
};
