services:
  collections-db:
    image: postgres:18
    container_name: collections-db
    environment:
      POSTGRES_DB: collections
      POSTGRES_USER: collections_user
      POSTGRES_PASSWORD: ${COLLECTIONS_DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - collections-db-data:/var/lib/postgresql

  keycloak-db:
    image: postgres:18
    container_name: keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak_user
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    volumes:
      - keycloak-db-data:/var/lib/postgresql

  keycloak:
    image: quay.io/keycloak/keycloak:26.7
    container_name: keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - keycloak-db

volumes:
  collections-db-data:
  keycloak-db-data: